-- delete code
Delete from items_in_orders_4 where orderid = 'ORDER100';
Delete from items_in_orders_4 where orderid = 'ORDER101';
Delete from items_in_orders_4 where orderid = 'ORDER102';
Delete from items_in_orders_4 where orderid = 'ORDER103';
Delete from items_in_orders_4 where orderid = 'ORDER104';
Delete from items_in_orders_4 where orderid = 'ORDER105';
Delete from items_in_orders_4 where orderid = 'ORDER106';
Delete from items_in_orders_4 where orderid = 'ORDER107';
Delete from items_in_orders_4 where orderid = 'ORDER108';
Delete from items_in_orders_4 where orderid = 'ORDER109';
Delete from items_in_orders_4 where orderid = 'ORDER110';
Delete from items_in_orders_4 where orderid = 'ORDER111';

Delete from items_in_orders_3 where (orderid = 'ORDER100' and stockid = 'STOCK100');
Delete from items_in_orders_3 where (orderid = 'ORDER101' and stockid = 'STOCK101');
Delete from items_in_orders_3 where (orderid = 'ORDER102' and stockid = 'STOCK102');
Delete from items_in_orders_3 where (orderid = 'ORDER103' and stockid = 'STOCK103');
Delete from items_in_orders_3 where (orderid = 'ORDER104' and stockid = 'STOCK104');
Delete from items_in_orders_3 where (orderid = 'ORDER105' and stockid = 'STOCK105');
Delete from items_in_orders_3 where (orderid = 'ORDER106' and stockid = 'STOCK106');
Delete from items_in_orders_3 where (orderid = 'ORDER107' and stockid = 'STOCK107');
Delete from items_in_orders_3 where (orderid = 'ORDER108' and stockid = 'STOCK108');
Delete from items_in_orders_3 where (orderid = 'ORDER109' and stockid = 'STOCK109');
Delete from items_in_orders_3 where (orderid = 'ORDER110' and stockid = 'STOCK110');
Delete from items_in_orders_3 where (orderid = 'ORDER111' and stockid = 'STOCK111');

Delete from items_in_orders_1 where (itemid = 'ITEM100');
Delete from items_in_orders_1 where (itemid = 'ITEM101');
Delete from items_in_orders_1 where (itemid = 'ITEM102');
Delete from items_in_orders_1 where (itemid = 'ITEM103');
Delete from items_in_orders_1 where (itemid = 'ITEM104');
Delete from items_in_orders_1 where (itemid = 'ITEM105');
Delete from items_in_orders_1 where (itemid = 'ITEM106');
Delete from items_in_orders_1 where (itemid = 'ITEM107');
Delete from items_in_orders_1 where (itemid = 'ITEM108');
Delete from items_in_orders_1 where (itemid = 'ITEM109');
Delete from items_in_orders_1 where (itemid = 'ITEM110');
Delete from items_in_orders_1 where (itemid = 'ITEM111');

Delete from stocks_in_bookstores where (stockid = 'STOCK100');
Delete from stocks_in_bookstores where (stockid = 'STOCK101');
Delete from stocks_in_bookstores where (stockid = 'STOCK102');
Delete from stocks_in_bookstores where (stockid = 'STOCK103');
Delete from stocks_in_bookstores where (stockid = 'STOCK104');
Delete from stocks_in_bookstores where (stockid = 'STOCK105');
Delete from stocks_in_bookstores where (stockid = 'STOCK106');
Delete from stocks_in_bookstores where (stockid = 'STOCK107');
Delete from stocks_in_bookstores where (stockid = 'STOCK108');
Delete from stocks_in_bookstores where (stockid = 'STOCK109');
Delete from stocks_in_bookstores where (stockid = 'STOCK110');
Delete from stocks_in_bookstores where (stockid = 'STOCK111');

Delete from complaints_on_orders where (complaintsid = 'COMPLAINT100');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT101');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT102');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT103');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT104');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT105');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT106');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT107');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT108');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT118');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT119');
Delete from complaints_on_orders where (complaintsid = 'COMPLAINT120');

Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT109');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT110');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT111');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT112');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT113');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT114');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT115');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT116');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT117');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT121');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT122');
Delete from complaints_on_bookstore where (complaintsid = 'COMPLAINT123');

Delete from orders where (orderid = 'ORDER100');
Delete from orders where (orderid = 'ORDER101');
Delete from orders where (orderid = 'ORDER102');
Delete from orders where (orderid = 'ORDER103');
Delete from orders where (orderid = 'ORDER104');
Delete from orders where (orderid = 'ORDER105');
Delete from orders where (orderid = 'ORDER106');
Delete from orders where (orderid = 'ORDER107');
Delete from orders where (orderid = 'ORDER108');
Delete from orders where (orderid = 'ORDER109');
Delete from orders where (orderid = 'ORDER110');
Delete from orders where (orderid = 'ORDER111');

Delete from complaints where (complaintsid = 'COMPLAINT100');
Delete from complaints where (complaintsid = 'COMPLAINT101');
Delete from complaints where (complaintsid = 'COMPLAINT102');
Delete from complaints where (complaintsid = 'COMPLAINT103');
Delete from complaints where (complaintsid = 'COMPLAINT104');
Delete from complaints where (complaintsid = 'COMPLAINT105');
Delete from complaints where (complaintsid = 'COMPLAINT106');
Delete from complaints where (complaintsid = 'COMPLAINT107');
Delete from complaints where (complaintsid = 'COMPLAINT108');
Delete from complaints where (complaintsid = 'COMPLAINT109');
Delete from complaints where (complaintsid = 'COMPLAINT110');
Delete from complaints where (complaintsid = 'COMPLAINT111');
Delete from complaints where (complaintsid = 'COMPLAINT112');
Delete from complaints where (complaintsid = 'COMPLAINT113');
Delete from complaints where (complaintsid = 'COMPLAINT114');
Delete from complaints where (complaintsid = 'COMPLAINT115');
Delete from complaints where (complaintsid = 'COMPLAINT116');
Delete from complaints where (complaintsid = 'COMPLAINT117');
Delete from complaints where (complaintsid = 'COMPLAINT118');
Delete from complaints where (complaintsid = 'COMPLAINT119');
Delete from complaints where (complaintsid = 'COMPLAINT120');
Delete from complaints where (complaintsid = 'COMPLAINT121');
Delete from complaints where (complaintsid = 'COMPLAINT122');
Delete from complaints where (complaintsid = 'COMPLAINT123');

Delete from customers where (cid = 'CUSTOMER100');
Delete from customers where (cid = 'CUSTOMER101');
Delete from customers where (cid = 'CUSTOMER102');
Delete from customers where (cid = 'CUSTOMER103');

Delete from magazines where pubid = 'PUB10';
Delete from magazines where pubid = 'PUB11';

Delete from publication where pubid = 'PUB10';
Delete from publication where pubid = 'PUB11';